spring:
  security:
    user:
      name: root
      password: root

  datasource:
    url: jdbc:mysql://localhost:3306/acciosecuritydb?createTableIfNoExists=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true